# Generated by Django 5.2.1 on 2025-05-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='lead_call_center',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lead_radius_distance',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lead_radius_zip',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lead_types',
        ),
    ]
