# Generated by Django 5.2.1 on 2025-05-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_rename_user_id_userdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100, unique=True)),
                ('last_synced_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_associations_id',
        ),
    ]
