# Generated by Django 5.2.1 on 2025-05-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_alter_synctracker_last_synced_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingsource',
            old_name='type',
            new_name='type_id',
        ),
        migrations.RemoveField(
            model_name='marketingsource',
            name='division',
        ),
    ]
