# Generated by Django 5.2.1 on 2025-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_rename_type_marketingsource_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingsourcetype',
            name='division',
        ),
        migrations.AlterField(
            model_name='marketingsource',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
