# Generated by Django 5.2.1 on 2025-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_remove_marketingsourcetype_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentOutcomeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_idx', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentoutcome',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointmentoutcome',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentoutcome',
            name='type_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
