# Generated by Django 5.2.1 on 2025-06-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0009_remove_appointment_marketing_task_id_and_more'),
    ]

    operations = [
        
    ]
