# Generated by Django 5.2.1 on 2025-06-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0010_remove_appointment_marketing_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='marketing_task_id',
        ),
    ]
