# Generated by Django 5.2.1 on 2025-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0011_remove_appointment_marketing_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='is_inactive',
            field=models.IntegerField(default=0),
        ),
    ]
