# Generated by Django 5.2.1 on 2025-06-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0013_hubspotcontact_hubspotdeal_hubspotsynchistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HubspotContact',
            new_name='Hubspot_Contact',
        ),
        migrations.RenameModel(
            old_name='HubspotDeal',
            new_name='Hubspot_Deal',
        ),
        migrations.RenameModel(
            old_name='HubspotSyncHistory',
            new_name='Hubspot_SyncHistory',
        ),
    ]
