# Generated by Django 5.2.1 on 2025-06-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0014_rename_hubspotcontact_hubspot_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Genius_Appointment',
        ),
        migrations.RenameModel(
            old_name='AppointmentOutcome',
            new_name='Genius_AppointmentOutcome',
        ),
        migrations.RenameModel(
            old_name='AppointmentOutcomeType',
            new_name='Genius_AppointmentOutcomeType',
        ),
        migrations.RenameModel(
            old_name='AppointmentService',
            new_name='Genius_AppointmentService',
        ),
        migrations.RenameModel(
            old_name='AppointmentType',
            new_name='Genius_AppointmentType',
        ),
        migrations.RenameModel(
            old_name='Division',
            new_name='Genius_Division',
        ),
        migrations.RenameModel(
            old_name='DivisionGroup',
            new_name='Genius_DivisionGroup',
        ),
        migrations.RenameModel(
            old_name='MarketingSource',
            new_name='Genius_MarketingSource',
        ),
        migrations.RenameModel(
            old_name='MarketingSourceType',
            new_name='Genius_MarketingSourceType',
        ),
        migrations.RenameModel(
            old_name='Prospect',
            new_name='Genius_Prospect',
        ),
        migrations.RenameModel(
            old_name='ProspectSource',
            new_name='Genius_ProspectSource',
        ),
        migrations.RenameModel(
            old_name='Quote',
            new_name='Genius_Quote',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Genius_Service',
        ),
        migrations.RenameModel(
            old_name='UserData',
            new_name='Genius_UserData',
        ),
    ]
