# Generated by Django 5.2.1 on 2025-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0015_rename_appointment_genius_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspot_contact',
            name='adgroupid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='ap_leadid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='campaign_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='clickcheck',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='clicktype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='lead_salesrabbit_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='msm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='original_lead_source_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='reference_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='search_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='tier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='trustedform_cert_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='vendorleadid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='vertical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_contact',
            name='original_lead_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
