# Generated by Django 5.2.1 on 2025-06-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0018_alter_marketsharp_company_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marketsharp_company',
            table=None,
        ),
    ]
