# Generated by Django 5.2.1 on 2025-06-04 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0019_alter_marketsharp_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing Source',
                'verbose_name_plural': 'Marketing Sources',
            },
        ),
        migrations.AlterField(
            model_name='marketsharp_producttype',
            name='name',
            field=models.CharField(default='Unnamed Product Type', max_length=255),
        ),
    ]
