# Generated by Django 5.2.1 on 2025-06-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0020_marketingsource_alter_marketsharp_producttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPro_Users',
            fields=[
                ('user_object_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_credit_apps', models.BooleanField(default=False)),
                ('search_other_users_estimates', models.BooleanField(default=False)),
                ('assigned_office', models.CharField(blank=True, max_length=255, null=True)),
                ('office_id', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unique_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('job_representative_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SalesPro User',
                'verbose_name_plural': 'SalesPro Users',
            },
        ),
        migrations.AlterModelTable(
            name='marketingsource',
            table='ingestion_marketingsource',
        ),
    ]
