# Generated by Django 5.2.1 on 2025-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0022_genius_usertitle_alter_genius_userdata_add_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genius_userdata',
            name='inactive_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genius_userdata',
            name='inactive_reason_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genius_userdata',
            name='inactive_reason_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genius_userdata',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
