# Generated by Django 5.2.1 on 2025-06-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0023_genius_userdata_inactive_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingSource',
        ),
    ]
