# Generated by Django 4.2.23 on 2025-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0024_delete_marketingsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_appointment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
