# Generated by Django 4.2.23 on 2025-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0025_alter_genius_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_appointment',
            name='complete_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='confirm_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='third_party_source_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
