# Generated by Django 4.2.23 on 2025-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0027_arrivy_customer_arrivy_synchistory_arrivy_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivy_booking',
            name='customer_id_raw',
            field=models.CharField(blank=True, help_text='Raw customer ID from API for debugging', max_length=50, null=True),
        ),
    ]
