# Generated by Django 4.2.23 on 2025-06-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0028_arrivy_booking_customer_id_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivy_booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='arrivy_booking',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Customer ID from API - no foreign key constraint', max_length=50, null=True),
        ),
    ]
