# Generated by Django 4.2.23 on 2025-06-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0030_rename_team_member_to_crew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrivy_Crew',
            new_name='Arrivy_Division',
        ),
        migrations.AlterModelOptions(
            name='arrivy_division',
            options={'verbose_name': 'Arrivy Division', 'verbose_name_plural': 'Arrivy Divisions'},
        ),
        migrations.AlterModelTable(
            name='arrivy_division',
            table='arrivy_division',
        ),
    ]
