# Generated by Django 4.2.23 on 2025-06-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0031_rename_arrivy_crew_arrivy_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='external_id',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='first_name',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='permission',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='image_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='address',
            new_name='complete_address',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='role',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='extra_fields',
            new_name='exact_location',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='can_turnon_location',
            new_name='is_address_geo_coded',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='is_online',
            new_name='use_lat_lng_address',
        ),
        migrations.RenameField(
            model_name='arrivy_division',
            old_name='phone',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='email',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='last_location_time',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='support_phone',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='support_sms',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='arrivy_division',
            name='username',
        ),
        migrations.AddField(
            model_name='arrivy_division',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
