# Generated by Django 4.2.23 on 2025-06-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0033_arrivy_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivy_Group',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url_safe_id', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('emergency', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('exact_location', models.JSONField(blank=True, null=True)),
                ('use_lat_lng_address', models.BooleanField(default=False)),
                ('is_address_geo_coded', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('image_id', models.CharField(blank=True, max_length=50, null=True)),
                ('image_path', models.URLField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_implicit', models.BooleanField(default=False)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('additional_addresses', models.JSONField(blank=True, null=True)),
                ('territory_ids', models.JSONField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arrivy Group',
                'verbose_name_plural': 'Arrivy Groups',
                'db_table': 'arrivy_group',
            },
        ),
    ]
