# Generated by Django 4.2.23 on 2025-06-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0034_arrivy_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arrivy_booking',
            table='ingestion_arrivy_booking',
        ),
        migrations.AlterModelTable(
            name='arrivy_customer',
            table='ingestion_arrivy_customer',
        ),
        migrations.AlterModelTable(
            name='arrivy_division',
            table='ingestion_arrivy_division',
        ),
        migrations.AlterModelTable(
            name='arrivy_entity',
            table='ingestion_arrivy_entity',
        ),
        migrations.AlterModelTable(
            name='arrivy_group',
            table='ingestion_arrivy_group',
        ),
        migrations.AlterModelTable(
            name='arrivy_synchistory',
            table='ingestion_arrivy_sync_history',
        ),
    ]
