# Generated by Django 4.2.23 on 2025-06-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0035_alter_arrivy_booking_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrivy_Division',
        ),
    ]
