# Generated by Django 4.2.23 on 2025-06-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0038_leadconduit_synchistory_leadconduit_lead_and_more'),
    ]

    operations = [
    ]
