# Generated by Django 4.2.23 on 2025-06-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0038_activeprospect_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salespro_appointment',
            table='ingestion_salespro_appointment',
        ),
        migrations.AlterModelTable(
            name='salespro_synchistory',
            table='ingestion_salespro_sync_history',
        ),
        migrations.AlterModelTable(
            name='salespro_users',
            table='ingestion_salespro_users',
        ),
    ]
