# Generated by Django 4.2.23 on 2025-06-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0040_leadconduit_synchistory_leadconduit_lead_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadconduit_event',
            new_name='ingestion_l_outcome_ff7575_idx',
            old_name='leadconduit_outcome_3a6dc9_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_event',
            new_name='ingestion_l_event_t_c6f3a6_idx',
            old_name='leadconduit_event_t_0a77b8_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_event',
            new_name='ingestion_l_start_t_bfc882_idx',
            old_name='leadconduit_start_t_8c72f7_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_event',
            new_name='ingestion_l_importe_947c4d_idx',
            old_name='leadconduit_importe_9845af_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_email_21c974_idx',
            old_name='leadconduit_email_de5921_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_phone_1_634c6d_idx',
            old_name='leadconduit_phone_1_855f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_state_594949_idx',
            old_name='leadconduit_state_64d8c0_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_submiss_edcaf5_idx',
            old_name='leadconduit_submiss_c55791_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_latest__7c8eab_idx',
            old_name='leadconduit_latest__e8653b_idx',
        ),
        migrations.AlterModelTable(
            name='leadconduit_event',
            table='ingestion_leadconduit_event',
        ),
        migrations.AlterModelTable(
            name='leadconduit_lead',
            table='ingestion_leadconduit_lead',
        ),
        migrations.AlterModelTable(
            name='leadconduit_synchistory',
            table='ingestion_leadconduit_sync_history',
        ),
    ]
