# Generated by Django 4.2.23 on 2025-06-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0042_hubspot_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_all_accessible_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_all_assigned_business_unit_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_all_owner_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_all_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_created_by_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_merged_object_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_object_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_object_source_detail_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_object_source_detail_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_object_source_detail_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_object_source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_object_source_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_object_source_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_owning_teams',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_read_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_shared_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_shared_user_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_unique_creation_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_updated_by_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_user_ids_of_all_notification_followers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_user_ids_of_all_notification_unfollowers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_user_ids_of_all_owners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='hs_was_imported',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
