# Generated by Django 4.2.23 on 2025-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0043_add_hubspot_system_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadconduit_lead',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
