# Generated by Django 4.2.23 on 2025-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0044_alter_leadconduit_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadconduit_lead',
            name='ad_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='disposition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='import_source',
            field=models.CharField(choices=[('api', 'API Import'), ('csv', 'CSV Import'), ('events', 'Events Extract')], default='api', max_length=50),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='landing_page',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='lead_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='referring_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leadconduit_lead',
            name='flow_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadconduit_lead',
            name='latest_event_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadconduit_lead',
            name='lead_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadconduit_lead',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='leadconduit_lead',
            index=models.Index(fields=['import_source'], name='ingestion_l_import__4f20fe_idx'),
        ),
        migrations.AddIndex(
            model_name='leadconduit_lead',
            index=models.Index(fields=['status'], name='ingestion_l_status_9fdac5_idx'),
        ),
        migrations.AddIndex(
            model_name='leadconduit_lead',
            index=models.Index(fields=['campaign'], name='ingestion_l_campaig_f8d600_idx'),
        ),
        migrations.AddIndex(
            model_name='leadconduit_lead',
            index=models.Index(fields=['utm_source'], name='ingestion_l_utm_sou_9b93ed_idx'),
        ),
        migrations.AddIndex(
            model_name='leadconduit_lead',
            index=models.Index(fields=['flow_name'], name='ingestion_l_flow_na_64cd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadconduit_lead',
            index=models.Index(fields=['source_name'], name='ingestion_l_source__1027f7_idx'),
        ),
    ]
