# Generated by Django 4.2.23 on 2025-06-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0045_update_leadconduit_lead_for_csv_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_analytics_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_analytics_source_data_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_analytics_source_data_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_createdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_lastmodifieddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_lead_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_lifecyclestage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='hs_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_area_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_disposition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_lead_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_rep_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_rep_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadconduit_lead',
            name='salesrabbit_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
