# Generated by Django 4.2.23 on 2025-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0046_add_salesrabbit_fields_to_leadconduit_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_appointment',
            name='add_user_id',
            field=models.BigIntegerField(),
        ),
    ]
