# Generated by Django 4.2.23 on 2025-06-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0048_arrivytask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivytask',
            options={'verbose_name': 'Arrivy Task', 'verbose_name_plural': 'Arrivy Tasks'},
        ),
        migrations.AlterModelTable(
            name='arrivytask',
            table='ingestion_arrivy_task',
        ),
    ]
