# Generated by Django 4.2.23 on 2025-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0050_arrivy_locationreport_arrivy_task_arrivy_taskstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRabbit_Lead',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField()),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SalesRabbit Lead',
                'verbose_name_plural': 'SalesRabbit Leads',
                'db_table': 'ingestion_salesrabbit_lead',
            },
        ),
        migrations.CreateModel(
            name='SalesRabbit_SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=100)),
                ('api_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SalesRabbit Sync History',
                'verbose_name_plural': 'SalesRabbit Sync Histories',
                'db_table': 'ingestion_salesrabbit_sync_history',
            },
        ),
    ]
