# Generated by Django 4.2.23 on 2025-06-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0051_salesrabbit_lead_salesrabbit_synchistory'),
    ]

    operations = [
    ]
