# Generated by Django 4.2.23 on 2025-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0052_auto_20250625_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrabbit_lead',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='salesrabbit_lead',
            old_name='created_time',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='salesrabbit_lead',
            old_name='updated_time',
            new_name='date_modified',
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='campaign_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='owner_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='phone_alternate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='status_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='street1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='street2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesrabbit_lead',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
