# Generated by Django 4.2.23 on 2025-06-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0053_rename_name_salesrabbit_lead_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivy_entity',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_group',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_group',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
