# Generated by Django 4.2.23 on 2025-06-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0054_alter_arrivy_entity_zipcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubspot_AppointmentContactAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.hubspot_appointment')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.hubspot_contact')),
            ],
            options={
                'db_table': 'ingestion_hubspot_appointment_contact_assoc',
                'unique_together': {('appointment', 'contact', 'association_type')},
            },
        ),
    ]
