# Generated by Django 4.2.23 on 2025-06-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0055_hubspot_appointmentcontactassociation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hubspot_appointmentcontactassociation',
            unique_together={('appointment', 'contact')},
        ),
        migrations.RemoveField(
            model_name='hubspot_appointmentcontactassociation',
            name='association_type',
        ),
    ]
