# Generated by Django 4.2.23 on 2025-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0056_alter_hubspot_appointmentcontactassociation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspot_appointmentcontactassociation',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointmentcontactassociation',
            name='contact_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='hubspot_appointmentcontactassociation',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='hubspot_appointmentcontactassociation',
            name='contact',
        ),
    ]
