# Generated by Django 4.2.23 on 2025-06-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0058_reportcategory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hubspot_appointmentcontactassociation',
            unique_together={('appointment_id', 'contact_id')},
        ),
    ]
