# Generated by Django 4.2.23 on 2025-06-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0059_alter_hubspot_appointmentcontactassociation_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportCategory',
        ),
    ]
