# Generated by Django 4.2.23 on 2025-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0061_hubspot_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubspot_ContactDivisionAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(blank=True, max_length=50, null=True)),
                ('division_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingestion_hubspot_contact_division_assoc',
                'unique_together': {('contact_id', 'division_id')},
            },
        ),
    ]
