# Generated by Django 4.2.23 on 2025-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0062_hubspot_contactdivisionassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubspot_ZipCode',
            fields=[
                ('zipcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'HubSpot ZipCode',
                'verbose_name_plural': 'HubSpot ZipCodes',
                'db_table': 'ingestion_hubspot_zipcode',
            },
        ),
    ]
