# Generated by Django 4.2.23 on 2025-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0065_genius_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_lead',
            name='with_dm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
