# Generated by Django 4.2.23 on 2025-07-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0066_fix_with_dm_field_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genius_Lead',
        ),
    ]
