# Generated by Django 4.2.23 on 2025-07-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0067_alter_genius_lead_invalid_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genius_Lead',
        ),
    ]
