# Generated by Django 4.2.23 on 2025-07-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0064_change_salespro_financing_to_textfield'),
    ] 

    operations = [
        migrations.CreateModel(
            name='Genius_MarketSharpSourceMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketsharp_id', models.CharField(max_length=128)),
                ('marketing_source_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
