# Generated by Django 4.2.23 on 2025-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0069_genius_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genius_MarketSharpSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marketsharp_id', models.CharField(blank=True, max_length=256, null=True)),
                ('source_name', models.CharField(blank=True, max_length=128, null=True)),
                ('inactive', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
