# Generated by Django 4.2.23 on 2025-07-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0071_create_genius_marketsharp_source_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_marketsharpsourcemaps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
