# Generated by Django 4.2.23 on 2025-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0072_alter_genius_marketsharpsourcemaps_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_marketsharpsourcemaps',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genius_marketsharpsourcemaps',
            name='marketsharp_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
