# Generated by Django 4.2.23 on 2025-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0073_alter_genius_marketsharpsourcemaps_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genius_lead',
            name='division',
        ),
        migrations.AddField(
            model_name='genius_lead',
            name='division_id',
            field=models.IntegerField(blank=True, db_column='division', null=True),
        ),
    ]
