# Generated by Django 4.2.23 on 2025-07-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0074_remove_genius_lead_division_genius_lead_division_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genius_MarketSharpSourceMaps',
            new_name='Genius_MarketSharpMarketingSourceMap',
        ),
    ]
