# Generated by Django 4.2.23 on 2025-07-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0075_rename_genius_marketsharpsourcemaps_genius_marketsharpmarketingsourcemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_source', models.CharField(max_length=50, unique=True)),
                ('credentials', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
                'db_table': 'api_credentials',
            },
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_source', models.CharField(max_length=50)),
                ('sync_type', models.CharField(max_length=100)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sync History',
                'verbose_name_plural': 'Sync Histories',
                'db_table': 'sync_history',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['crm_source', 'sync_type'], name='sync_histor_crm_sou_43076f_idx'), models.Index(fields=['start_time'], name='sync_histor_start_t_7b1b99_idx'), models.Index(fields=['status'], name='sync_histor_status_ebf158_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_source', models.CharField(max_length=50)),
                ('sync_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_size', models.IntegerField(default=500)),
                ('retry_count', models.IntegerField(default=3)),
                ('retry_delay', models.IntegerField(default=1)),
                ('field_mappings', models.JSONField(default=dict)),
                ('api_settings', models.JSONField(default=dict)),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Configuration',
                'verbose_name_plural': 'Sync Configurations',
                'db_table': 'sync_configuration',
                'unique_together': {('crm_source', 'sync_type')},
            },
        ),
    ]
