# Generated by Django 4.2.23 on 2025-07-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0077_salespro_creditapplication_salespro_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespro_customer',
            name='company_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='crm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='crm_source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='estimate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
