# Generated by Django 4.2.23 on 2025-07-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0078_fix_salespro_customer_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespro_customer',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
