# Generated by Django 4.2.23 on 2025-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0080_alter_salespro_creditapplication_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespro_estimate',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_estimate',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_measuresheet',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_measuresheet',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_payment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_payment',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salespro_useractivity',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
