# Generated by Django 4.2.23 on 2025-07-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0083_fix_salespro_datetime_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespro_useractivity',
            options={'ordering': ['created_at'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterUniqueTogether(
            name='salespro_useractivity',
            unique_together={('created_at', 'user_id', 'activity_note')},
        ),
    ]
