# Generated by Django 4.2.23 on 2025-07-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0084_update_user_activity_remove_id_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespro_measuresheet',
            options={'ordering': ['created_at'], 'verbose_name': 'Measure Sheet', 'verbose_name_plural': 'Measure Sheets'},
        ),
        migrations.AlterUniqueTogether(
            name='salespro_measuresheet',
            unique_together={('created_at', 'updated_at', 'estimate_id', 'measure_sheet_item_name')},
        ),
    ]
