# Generated by Django 4.2.23 on 2025-07-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0085_update_measure_sheet_remove_id_add_ordering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesPro_EstimatePriceBreakdown',
        ),
        migrations.DeleteModel(
            name='SalesPro_GeographicHotspot',
        ),
    ]
