# Generated by Django 4.2.23 on 2025-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0086_delete_salespro_estimatepricebreakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPro_EstimatePriceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='genius_appointment',
            old_name='third_party_source_id',
            new_name='hubspot_appointment_id',
        ),
        migrations.RemoveField(
            model_name='genius_prospect',
            name='third_party_source_id',
        ),
        migrations.AddField(
            model_name='genius_prospect',
            name='hubspot_contact_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
