# Generated by Django 4.2.23 on 2025-07-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0087_salespro_estimatepricebreakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubspot_GeniusUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hs_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hs_createdate', models.DateTimeField(blank=True, null=True)),
                ('hs_lastmodifieddate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('arrivy_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('division_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('merged_record_ids', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('object_create_datetime', models.DateTimeField(blank=True, null=True)),
                ('object_last_modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_assigned_date', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.BigIntegerField(unique=True)),
                ('record_source', models.CharField(blank=True, max_length=255, null=True)),
                ('record_source_detail_1', models.CharField(blank=True, max_length=255, null=True)),
                ('record_source_detail_2', models.CharField(blank=True, max_length=255, null=True)),
                ('record_source_detail_3', models.CharField(blank=True, max_length=255, null=True)),
                ('title_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('user_account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_status_inactive', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HubSpot Genius User',
                'verbose_name_plural': 'HubSpot Genius Users',
                'db_table': 'ingestion_hubspot_geniususer',
            },
        ),
    ]
