# Generated by Django 4.2.23 on 2025-07-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0088_hubspot_geniususer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='created_by_user_id',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='merged_record_ids',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='object_create_datetime',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='object_last_modified_datetime',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='owner_assigned_date',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='record_source',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='record_source_detail_1',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='record_source_detail_2',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='record_source_detail_3',
        ),
        migrations.RemoveField(
            model_name='hubspot_geniususer',
            name='updated_by_user_id',
        ),
    ]
