# Generated by Django 4.2.23 on 2025-07-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0090_remove_hubspot_geniususer_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspot_appointment',
            name='appointment_confirmed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='arrivy_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='arrivy_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='arrivy_result_full_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='arrivy_salesrep_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='arrivy_salesrep_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='arrivy_status_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='created_by_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='div_cancel_reasons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='f9_tfuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='genius_quote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='genius_quote_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='genius_quote_response_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='genius_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='genius_response_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='genius_resubmit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='qc_cancel_reasons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='salespro_consider_solar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='salespro_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='salespro_estimate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='set_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_appointment',
            name='sourcefield',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='add_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='complete_outcome_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='complete_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='confirm_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='marketing_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
