# Generated by Django 4.2.23 on 2025-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0091_update_hubspot_appointment_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_contact',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_division',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
