# Generated by Django 4.2.23 on 2025-07-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0092_alter_hubspot_appointment_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='salespro_last_price_offered',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='salespro_one_year_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
