# Generated by Django 4.2.23 on 2025-07-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0094_alter_hubspot_contact_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_hsconta_14fe37_idx',
            old_name='hubspot_con_hsconta_302e31_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_appoint_da049d_idx',
            old_name='hubspot_con_appoint_b3c9f2_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_email_96a399_idx',
            old_name='hubspot_con_email_968354_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_phone1_61f1ad_idx',
            old_name='hubspot_con_phone1_f4ed7f_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_appoint_e8b675_idx',
            old_name='hubspot_con_appoint_3dd444_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_appoint_8d7fd5_idx',
            old_name='hubspot_con_appoint_9278b5_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_first_n_10c800_idx',
            old_name='hubspot_con_first_n_4cf7c4_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_city_967869_idx',
            old_name='hubspot_con_city_bb55c8_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_object__401826_idx',
            old_name='hubspot_con_object__a1ffc5_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_created_a31d9a_idx',
            old_name='hubspot_con_created_3614ff_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspot_contact',
            new_name='ingestion_h_updated_d5cb82_idx',
            old_name='hubspot_con_updated_11ed68_idx',
        ),
        migrations.AlterModelTable(
            name='hubspot_contact',
            table=None,
        ),
    ]
