# Generated by Django 4.2.23 on 2025-07-22 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0097_alertrule_alertmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesRabbit_SyncHistory',
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='created_in_sync',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='salesrabbit_lead',
            index=models.Index(fields=['date_modified'], name='ingestion_s_date_mo_91d02a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrabbit_lead',
            index=models.Index(fields=['email'], name='ingestion_s_email_ce9731_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrabbit_lead',
            index=models.Index(fields=['status'], name='ingestion_s_status_168b61_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrabbit_lead',
            index=models.Index(fields=['campaign_id'], name='ingestion_s_campaig_fa1b47_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrabbit_lead',
            index=models.Index(fields=['user_id'], name='ingestion_s_user_id_be1e0f_idx'),
        ),
    ]
