# Generated by Django 4.2.23 on 2025-07-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0098_delete_salesrabbit_synchistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genius_userdata',
            name='primary_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
