# Generated by Django 4.2.23 on 2025-07-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0101_leadresult_estimate_id_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespro_useractivity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
