# Generated by Django 4.2.23 on 2025-07-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0102_alter_salespro_useractivity_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesPro_EstimatePriceBreakdown',
        ),
    ]
