# Generated by Django 4.2.23 on 2025-07-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0103_delete_salespro_estimatepricebreakdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesPro_MeasureSheet',
        ),
    ]
