# Generated by Django 4.2.23 on 2025-07-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0104_remove_measuresheet_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesPro_Appointment',
        ),
        migrations.DeleteModel(
            name='SalesPro_SyncHistory',
        ),
        migrations.DeleteModel(
            name='SalesPro_Users',
        ),
        migrations.AlterModelTable(
            name='salespro_creditapplication',
            table='ingestion_salespro_credit_application',
        ),
        migrations.AlterModelTable(
            name='salespro_leadresult',
            table='ingestion_salespro_lead_result',
        ),
        migrations.AlterModelTable(
            name='salespro_payment',
            table='ingestion_salespro_payment',
        ),
    ]
