# Generated by Django 4.2.23 on 2025-07-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0105_delete_salespro_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrabbit_lead',
            old_name='created_in_sync',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='salesrabbit_lead',
            old_name='synced_at',
            new_name='updated_at',
        ),
    ]
