# Generated by Django 4.2.23 on 2025-08-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0106_rename_salesrabbit_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='appointment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
