# Generated by Django 4.2.23 on 2025-07-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0107_remove_callrail_synced_at'),
    ]

    operations = [
        # These field renames have already been applied or were never needed
        # Keeping migration for consistency with migration history
    ]
