# Generated by Django 4.2.23 on 2025-08-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0108_rename_salesrabbit_sync_fields'),
    ]

    operations = [
        # appointment and files fields already exist in the model
        # Keeping migration for consistency with migration history
    ]
