# Generated by Django 4.2.23 on 2025-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0109_salesrabbit_lead_appointment_salesrabbit_lead_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadConduit_Event',
        ),
        migrations.DeleteModel(
            name='LeadConduit_Lead',
        ),
        migrations.DeleteModel(
            name='LeadConduit_SyncHistory',
        ),
    ]
