# Generated by Django 4.2.23 on 2025-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0109_salesrabbit_lead_appointment_salesrabbit_lead_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveProspect_Event',
        ),
        migrations.DeleteModel(
            name='ActiveProspect_Lead',
        ),
        migrations.DeleteModel(
            name='ActiveProspect_SyncHistory',
        ),
        migrations.DeleteModel(
            name='LeadConduit_Event',
        ),
        migrations.DeleteModel(
            name='LeadConduit_Lead',
        ),
        migrations.DeleteModel(
            name='LeadConduit_SyncHistory',
        ),
        migrations.RenameField(
            model_name='salesrabbit_lead',
            old_name='created_in_sync',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='salesrabbit_lead',
            old_name='synced_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='appointment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrabbit_lead',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
