# Generated by Django 4.2.23 on 2025-08-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0110_delete_activeprospect_event_and_more'),
    ]

    operations = [
        # Create LeadConduit models only
        migrations.CreateModel(
            name='LeadConduit_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('lead_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField()),
                ('source_data', models.JSONField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingestion_leadconduit_event',
                'indexes': [
                    models.Index(fields=['lead_id'], name='leadconduit_event_lead_id_idx'),
                    models.Index(fields=['type'], name='leadconduit_event_type_idx'),
                    models.Index(fields=['timestamp'], name='leadconduit_event_timestamp_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='LeadConduit_Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingestion_leadconduit_lead',
                'indexes': [
                    models.Index(fields=['email'], name='leadconduit_lead_email_idx'),
                    models.Index(fields=['phone'], name='leadconduit_lead_phone_idx'),
                    models.Index(fields=['source'], name='leadconduit_lead_source_idx'),
                    models.Index(fields=['lead_timestamp'], name='leadconduit_lead_timestamp_idx'),
                ],
            },
        ),
    ]
