# Generated by Django 4.2.23 on 2025-08-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0114_cleanup_migration_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveProspect_Event',
        ),
        migrations.DeleteModel(
            name='ActiveProspect_Lead',
        ),
        migrations.DeleteModel(
            name='ActiveProspect_SyncHistory',
        ),
        migrations.DeleteModel(
            name='LeadConduit_Event',
        ),
        migrations.DeleteModel(
            name='LeadConduit_Lead',
        ),
        migrations.RemoveField(
            model_name='salesrabbit_lead',
            name='created_in_sync',
        ),
        migrations.RemoveField(
            model_name='salesrabbit_lead',
            name='synced_at',
        ),
    ]
