# Generated by Django 4.2.23 on 2025-08-08 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0117_add_hge_and_metadata_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(help_text='Internal name for the sheet', max_length=100, unique=True)),
                ('sheet_id', models.CharField(help_text='Google Sheets ID from URL', max_length=100)),
                ('tab_name', models.CharField(help_text='Tab/worksheet name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('header_row', models.IntegerField(default=1, help_text='Row number containing headers')),
                ('data_start_row', models.IntegerField(default=2, help_text='First row containing data')),
                ('column_mapping', models.JSONField(default=dict, help_text='Map sheet columns to model fields')),
                ('ignored_columns', models.JSONField(default=list, help_text='List of columns to ignore')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_sheet_modified', models.DateTimeField(blank=True, null=True)),
                ('target_model', models.CharField(help_text='Django model class name', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingestion_gsheet_config',
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetMarketingLead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_row_number', models.IntegerField(blank=True, help_text='Original row number in sheet', null=True)),
                ('sheet_last_modified', models.DateTimeField(blank=True, help_text='Sheet last modification time', null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('leads', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Complete row data from sheet')),
            ],
            options={
                'db_table': 'ingestion_gsheet_marketing_lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
