# Generated by Django 4.2.23 on 2025-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0119_remove_googlesheetconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheetmarketinglead',
            options={'ordering': ['-lead_created_at', '-created_at'], 'verbose_name': 'Google Sheet Marketing Lead', 'verbose_name_plural': 'Google Sheet Marketing Leads'},
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_email_0ca3b5_idx',
            old_name='ingestion_l_email_ff7575_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_state_7164a3_idx',
            old_name='ingestion_l_state_3a6dc9_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_flow_na_b9b8a0_idx',
            old_name='ingestion_l_flow_na_21f4b7_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_outcome_f226b0_idx',
            old_name='ingestion_l_outcome_1a6dc9_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_submitt_25866b_idx',
            old_name='ingestion_l_submitt_2b7b89_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_ownerid_0bb7ee_idx',
            old_name='ingestion_l_ownerid_hge_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_salesra_40847e_idx',
            old_name='ingestion_l_salesrabbit_hge_idx',
        ),
        migrations.RenameIndex(
            model_name='leadconduit_lead',
            new_name='ingestion_l_owner_h_00255b_idx',
            old_name='ingestion_l_owner_submitted_idx',
        ),
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='date',
        ),
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='source',
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='adgroup_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='adgroup_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='after_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='appointment_outcome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='appointment_outcome_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='appt_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='appt_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='appt_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='appt_result_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='appt_set_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='call_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='call_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='call_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='call_recording',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='callback_review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='cancel_job_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='click_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='click_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='connection_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='contact_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='csr_disposition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='event_show_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='event_show_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='f9_last_campaign',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='f9_list_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='f9_sys_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='first_call_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='form_submit_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='genius_division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='genius_marketing_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='google_ads_campaign_rename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='hold_time',
            field=models.IntegerField(blank=True, help_text='Hold time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='keyword',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='lead_created_at',
            field=models.DateTimeField(blank=True, help_text='created_at from sheet', null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='lead_set',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='lead_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='manager_followup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='marketing_zip_check',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='marketsharp_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='marketsharp_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='multiple_inquiry',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='no_set_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='page_source_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='page_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='preferred_appt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='recording_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='set_appt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='spouses_present',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='total_job_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='sheet_row_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['phone_number', 'lead_created_at'], name='ingestion_g_phone_n_cce76e_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['email_address', 'lead_created_at'], name='ingestion_g_email_a_754a92_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['first_name', 'last_name'], name='ingestion_g_first_n_c49c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['utm_campaign', 'division'], name='ingestion_g_utm_cam_78ee65_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['genius_marketing_source', 'division'], name='ingestion_g_genius__ea6dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['lead_created_at', 'utm_campaign'], name='ingestion_g_lead_cr_b1c091_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['lead_set', 'division'], name='ingestion_g_lead_se_706a05_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['connection_status', 'lead_type'], name='ingestion_g_connect_129c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['appt_result', 'appointment_outcome'], name='ingestion_g_appt_re_7cb0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['sheet_row_number'], name='ingestion_g_sheet_r_66b4be_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['created_at'], name='ingestion_g_created_732877_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['lead_created_at'], name='ingestion_g_lead_cr_47eb62_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['division', 'lead_created_at', 'lead_set'], name='ingestion_g_divisio_20c66d_idx'),
        ),
    ]
