# Generated by Django 4.2.23 on 2025-08-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0120_update_gsheet_marketing_lead_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='adgroup_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='after_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='appointment_outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='appointment_outcome_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='appt_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='appt_result_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='appt_set_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='call_recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='click_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='click_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='connection_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='contact_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='csr_disposition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='event_show_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='event_show_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='f9_last_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='f9_list_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='genius_marketing_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='google_ads_campaign_rename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='last_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='lead_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='marketing_zip_check',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='marketsharp_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='marketsharp_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='no_set_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='page_source_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='page_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
