# Generated by Django 4.2.23 on 2025-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0122_convert_boolean_fields_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='lead_set',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='manager_followup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='multiple_inquiry',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='spouses_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
