# Generated by Django 4.2.23 on 2025-08-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0121_alter_googlesheetmarketinglead_adgroup_name_and_more'),
        ('ingestion', '0123_convert_fields_to_boolean'),
    ]

    operations = [
    ]
