# Generated by Django 4.2.23 on 2025-08-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0124_merge_20250808_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='id',
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='sheet_row_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
