# Generated by Django 4.2.23 on 2025-08-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0125_use_sheet_row_number_as_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='marketing_channel',
            field=models.CharField(blank=True, help_text='Marketing channel (GMB, Google Ads, Bing Ads, Direct Mail, Web Organic, FM Flyer, etc.)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['marketing_channel', 'division'], name='ingestion_g_marketi_5f1ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['marketing_channel', 'lead_created_at'], name='ingestion_g_marketi_6029a0_idx'),
        ),
    ]
