# Generated by Django 4.2.23 on 2025-08-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0125_use_sheet_row_number_as_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='arrivy_appt_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='arrivy_confirm_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='salespro_both_homeowners',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='salespro_deadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='salespro_requested_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='spouses_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_contact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
