# Generated by Django 4.2.23 on 2025-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0126_alter_hubspot_appointment_arrivy_appt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='canvasser_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
