# Generated by Django 4.2.23 on 2025-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0127_alter_hubspot_appointment_canvasser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='canvasser_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
