# Generated by Django 4.2.23 on 2025-08-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0128_alter_hubspot_appointment_canvasser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='arrivy_appt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubspot_appointment',
            name='arrivy_confirm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
