# Generated by Django 4.2.23 on 2025-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0129_alter_hubspot_appointment_arrivy_appt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspot_appointment',
            name='genius_prospect_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
