# Generated by Django 4.2.23 on 2025-08-12 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0130_hubspot_appointment_genius_prospect_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetMarketingSpend',
            fields=[
                ('sheet_row_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_last_modified', models.DateTimeField(blank=True, help_text='Sheet last modification time', null=True)),
                ('spend_date', models.DateField(blank=True, help_text='Date of marketing spend', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Marketing cost amount', max_digits=12, null=True)),
                ('division', models.CharField(blank=True, help_text='Marketing division', max_length=50, null=True)),
                ('channel', models.CharField(blank=True, help_text='Marketing channel', max_length=50, null=True)),
                ('campaign', models.CharField(blank=True, help_text='Marketing campaign name', max_length=100, null=True)),
                ('event_start_date', models.DateField(blank=True, help_text='Event start date', null=True)),
                ('event_end_date', models.DateField(blank=True, help_text='Event end date', null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Complete row data from sheet')),
            ],
            options={
                'verbose_name': 'Google Sheet Marketing Spend',
                'verbose_name_plural': 'Google Sheet Marketing Spends',
                'db_table': 'ingestion_gsheet_marketing_spend',
                'ordering': ['-spend_date', '-created_at'],
                'indexes': [models.Index(fields=['spend_date', 'division'], name='ingestion_g_spend_d_9e15af_idx'), models.Index(fields=['division', 'channel'], name='ingestion_g_divisio_822ad8_idx'), models.Index(fields=['campaign', 'spend_date'], name='ingestion_g_campaig_196026_idx'), models.Index(fields=['channel', 'campaign'], name='ingestion_g_channel_015cfa_idx'), models.Index(fields=['spend_date', 'channel'], name='ingestion_g_spend_d_908d7a_idx'), models.Index(fields=['sheet_row_number'], name='ingestion_g_sheet_r_20263a_idx'), models.Index(fields=['created_at'], name='ingestion_g_created_d4003e_idx'), models.Index(fields=['spend_date'], name='ingestion_g_spend_d_992744_idx'), models.Index(fields=['division', 'spend_date', 'cost'], name='ingestion_g_divisio_6cd262_idx')],
            },
        ),
    ]
