# Generated by GitHub Copilot on 2025-08-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0131_googlesheetmarketingspend'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPro_User',
            fields=[
                ('user_object_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_available_to_call', models.BooleanField(default=False)),
                ('can_activate_users', models.BooleanField(default=False)),
                ('can_change_settings', models.BooleanField(default=False)),
                ('can_submit_credit_apps', models.BooleanField(default=False)),
                ('disable_change_company', models.BooleanField(default=False)),
                ('company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_office', models.CharField(blank=True, max_length=50, null=True)),
                ('allowed_offices', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('deactivated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_salespro_users',
                'verbose_name': 'SalesPro User',
                'verbose_name_plural': 'SalesPro Users',
            },
        ),
        migrations.AddIndex(
            model_name='salespro_user',
            index=models.Index(fields=['username'], name='ingestion_sa_username_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_user',
            index=models.Index(fields=['email'], name='ingestion_sa_email_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_user',
            index=models.Index(fields=['company_id'], name='ingestion_sa_company_idx'),
        ),
    ]
