# Generated by GitHub Copilot on 2025-08-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0132_salespro_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPro_Office',
            fields=[
                ('office_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_search_all_estimates', models.BooleanField(default=False)),
                ('last_edit_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_salespro_offices',
                'verbose_name': 'SalesPro Office',
                'verbose_name_plural': 'SalesPro Offices',
            },
        ),
        migrations.AddIndex(
            model_name='salespro_office',
            index=models.Index(fields=['company_id'], name='ingestion_sa_office_company_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_office',
            index=models.Index(fields=['name'], name='ingestion_sa_office_name_idx'),
        ),
    ]
