# Generated by Django 4.2.23 on 2025-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0133_salespro_office_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salespro_office',
            new_name='ingestion_s_company_0aa988_idx',
            old_name='ingestion_sa_office_company_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_office',
            new_name='ingestion_s_name_fab35d_idx',
            old_name='ingestion_sa_office_name_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_user',
            new_name='ingestion_s_usernam_25cb00_idx',
            old_name='ingestion_sa_username_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_user',
            new_name='ingestion_s_email_6a76a7_idx',
            old_name='ingestion_sa_email_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_user',
            new_name='ingestion_s_company_5b0c92_idx',
            old_name='ingestion_sa_company_idx',
        ),
        migrations.AlterField(
            model_name='salespro_user',
            name='allowed_offices',
            field=models.TextField(blank=True, help_text='JSON array from CSV of Office pointers', null=True),
        ),
    ]
