# Generated by Django 4.2.23 on 2025-08-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0134_rename_ingestion_sa_office_company_idx_ingestion_s_company_0aa988_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salespro_office',
            new_name='ingestion_s_company_cb7ece_idx',
            old_name='ingestion_s_company_0aa988_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_office',
            new_name='ingestion_s_name_c00825_idx',
            old_name='ingestion_s_name_fab35d_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_user',
            new_name='ingestion_s_usernam_56370e_idx',
            old_name='ingestion_s_usernam_25cb00_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_user',
            new_name='ingestion_s_email_34a55b_idx',
            old_name='ingestion_s_email_6a76a7_idx',
        ),
        migrations.RenameIndex(
            model_name='salespro_user',
            new_name='ingestion_s_company_3bed4f_idx',
            old_name='ingestion_s_company_5b0c92_idx',
        ),
        migrations.AlterModelTable(
            name='salespro_office',
            table='ingestion_salespro_office',
        ),
        migrations.AlterModelTable(
            name='salespro_user',
            table='ingestion_salespro_user',
        ),
    ]
