# Generated by Django 4.2.23 on 2025-08-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0135_rename_ingestion_s_company_0aa988_idx_ingestion_s_company_cb7ece_idx_and_more'),
        ('ingestion', 'migrate_arrivy_sync_history'),
    ]

    operations = [
    ]
