# Generated manually for Arrivy_Booking model

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0135_rename_ingestion_s_company_0aa988_idx_ingestion_s_company_cb7ece_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivy_Booking',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url_safe_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_datetime_original_iso_str', models.CharField(blank=True, max_length=50, null=True)),
                ('end_datetime_original_iso_str', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('task_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_estimate', models.IntegerField(blank=True, null=True)),
                ('actual_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_all_day', models.BooleanField(default=False)),
                ('enable_time_window_display', models.BooleanField(default=False)),
                ('unscheduled', models.BooleanField(default=False)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('customer_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('exact_location', models.JSONField(blank=True, null=True)),
                ('is_address_geo_coded', models.BooleanField(default=False)),
                ('use_lat_lng_address', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('assigned_team_members', models.JSONField(blank=True, null=True)),
                ('team_member_ids', models.TextField(blank=True, null=True)),
                ('entity_ids', models.JSONField(blank=True, null=True)),
                ('crew_ids', models.JSONField(blank=True, null=True)),
                ('worker_ids', models.JSONField(blank=True, null=True)),
                ('number_of_workers_required', models.IntegerField(blank=True, null=True)),
                ('resource_ids', models.JSONField(blank=True, null=True)),
                ('template_id', models.CharField(blank=True, max_length=50, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('template_extra_fields', models.JSONField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('external_type', models.CharField(blank=True, max_length=100, null=True)),
                ('external_resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('linked_internal_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('linked_external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('is_linked', models.BooleanField(default=False)),
                ('route_id', models.CharField(blank=True, max_length=50, null=True)),
                ('route_name', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_route_id', models.CharField(blank=True, max_length=50, null=True)),
                ('routes', models.JSONField(blank=True, null=True)),
                ('entity_routes', models.JSONField(blank=True, null=True)),
                ('additional_addresses', models.JSONField(blank=True, null=True)),
                ('current_destination', models.JSONField(blank=True, null=True)),
                ('notifications', models.JSONField(blank=True, null=True)),
                ('outbound_sms_count', models.IntegerField(blank=True, null=True)),
                ('inbound_sms_count', models.IntegerField(blank=True, null=True)),
                ('outbound_email_count', models.IntegerField(blank=True, null=True)),
                ('inbound_email_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_text', models.TextField(blank=True, null=True)),
                ('travel_time', models.CharField(blank=True, max_length=255, null=True)),
                ('wait_time', models.CharField(blank=True, max_length=255, null=True)),
                ('task_time', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time', models.CharField(blank=True, max_length=255, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('document_ids', models.JSONField(blank=True, null=True)),
                ('file_ids', models.JSONField(blank=True, null=True)),
                ('files', models.JSONField(blank=True, null=True)),
                ('forms', models.JSONField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, null=True)),
                ('entity_confirmation_statuses', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arrivy Booking',
                'verbose_name_plural': 'Arrivy Bookings',
                'db_table': 'ingestion_arrivy_booking',
            },
        ),
    ]
