# Generated by Django 4.2.23 on 2025-08-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0136_merge_20250814_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivy_entity',
            name='can_manage_crews',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_entity',
            name='can_manage_entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_entity',
            name='can_manage_resources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_entity',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_entity',
            name='email_invitation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_entity',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
