# Generated by Django 4.2.23 on 2025-08-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0137_add_entity_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivy_entity',
            old_name='synced_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='arrivy_entity',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='arrivy_entity',
            name='updated_time',
        ),
    ]
