# Generated by Django 4.2.23 on 2025-08-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0138_cleanup_entity_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivy_group',
            old_name='synced_at',
            new_name='updated_at',
        ),
    ]
