# Generated by Django 4.2.23 on 2025-08-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0139_rename_group_synced_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivy_group',
            old_name='created_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='arrivy_group',
            old_name='updated_time',
            new_name='updated',
        ),
    ]
