# Generated by Django 4.2.23 on 2025-08-14 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0140_update_arrivy_group_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivy_taskstatus',
            old_name='created_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='arrivy_taskstatus',
            old_name='updated_time',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='additional_addresses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='created_by_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='crew_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='current_destination',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_exact_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='customer_zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='document_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='due_datetime_original_iso_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='end_datetime_original_iso_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='end_datetime_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='entity_confirmation_statuses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='entity_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='entity_routes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='external_resource_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='external_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='file_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='internal_route_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='is_customer_address_geo_coded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='is_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='is_supply_provided_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='is_supply_returned_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='linked_external_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='linked_internal_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='mileage_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='number_of_workers_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='resource_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='route_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='routes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='self_scheduling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='series_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='skill_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='start_datetime_original_iso_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='start_datetime_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='status_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='template_extra_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='template_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='updated_by_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='url_safe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='use_lat_lng_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_task',
            name='worker_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='forms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_task',
            name='task_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
