# Generated by Django 4.2.23 on 2025-08-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0136_add_arrivy_booking_model'),
        ('ingestion', '0142_arrivy_task_customer_email_and_more'),
    ]

    operations = [
    ]
