# Generated by Django 4.2.23 on 2025-08-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0143_merge_20250815_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='require_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='require_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='type_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_taskstatus',
            name='visible_to_customer',
            field=models.BooleanField(default=False),
        ),
    ]
