# Generated by Django 4.2.23 on 2025-08-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0144_add_task_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivy_taskstatus',
            name='require_rating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_taskstatus',
            name='require_signature',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='arrivy_taskstatus',
            name='visible_to_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
