# Generated by Django 4.2.23 on 2025-08-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0145_fix_task_status_boolean_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrivy_TaskStatus',
            new_name='Arrivy_Status',
        ),
        migrations.AlterModelOptions(
            name='arrivy_status',
            options={'verbose_name': 'Arrivy Status', 'verbose_name_plural': 'Arrivy Statuses'},
        ),
        migrations.AlterModelTable(
            name='arrivy_status',
            table='ingestion_arrivy_status',
        ),
    ]
