# Generated by Django 4.2.23 on 2025-08-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0146_rename_taskstatus_to_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivy_status',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrivy_status',
            name='status_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
