# Generated by Django 4.2.23 on 2025-08-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0147_add_status_fields'),
    ]

    operations = [
        # Remove the Arrivy_LocationReport table
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS ingestion_arrivy_location_report CASCADE;",
            reverse_sql="-- Cannot reverse DROP TABLE operation"
        ),
        # Remove the Arrivy_SyncHistory table
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS ingestion_arrivy_sync_history CASCADE;",
            reverse_sql="-- Cannot reverse DROP TABLE operation"
        ),
    ]
