# Generated by Django 4.2.23 on 2025-08-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0148_remove_arrivy_locationreport_synchistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrivy_LocationReport',
        ),
        migrations.DeleteModel(
            name='Arrivy_SyncHistory',
        ),
    ]
