# Generated by Django 4.2.23 on 2025-08-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0126_add_marketing_channel_to_gsheet_marketing_lead'),
        ('ingestion', '0149_delete_arrivy_locationreport_and_more'),
    ]

    operations = [
    ]
