# Generated by Django 4.2.23 on 2025-08-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0152_alter_googlesheetmarketinglead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheetmarketinglead',
            options={'ordering': ['-created_at', '-sync_created_at'], 'verbose_name': 'Google Sheet Marketing Lead', 'verbose_name_plural': 'Google Sheet Marketing Leads'},
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='ingestion_g_phone_n_cce76e_idx',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='ingestion_g_email_a_754a92_idx',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='ingestion_g_lead_cr_b1c091_idx',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='ingestion_g_lead_cr_47eb62_idx',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='ingestion_g_divisio_20c66d_idx',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='ingestion_g_marketi_6029a0_idx',
        ),
        migrations.RenameField(
            model_name='googlesheetmarketinglead',
            old_name='lead_created_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['phone_number', 'created_at'], name='ingestion_g_phone_n_c2eb51_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['email_address', 'created_at'], name='ingestion_g_email_a_b821c8_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['created_at', 'utm_campaign'], name='ingestion_g_created_9add92_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['marketing_channel', 'created_at'], name='ingestion_g_marketi_2754b3_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['created_at'], name='ingestion_g_created_732877_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['division', 'created_at', 'lead_set'], name='ingestion_g_divisio_449be4_idx'),
        ),
    ]
