# Generated by Django 4.2.23 on 2025-08-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0158_add_five9_contact'),
    ]

    operations = [
        # This migration acknowledges the existing hubspot_contact table
        # No actual operations needed since the table already exists
    ]
