# Generated by Django 4.2.23 on 2025-08-25 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0159_create_hubspot_contact_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='five9contact',
            options={'managed': True, 'verbose_name': 'Five9 Contact', 'verbose_name_plural': 'Five9 Contacts'},
        ),
        migrations.AlterModelOptions(
            name='hubspot_contact',
            options={'managed': True, 'ordering': ['-lastmodifieddate', '-createdate'], 'verbose_name': 'HubSpot Contact', 'verbose_name_plural': 'HubSpot Contacts'},
        ),
        migrations.AlterModelTableComment(
            name='five9contact',
            table_comment='Five9 Contact data stored in ingestion schema',
        ),
        migrations.AlterModelTableComment(
            name='hubspot_contact',
            table_comment='Hubspot Contact data stored in ingestion schema',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='gsheet_mark_marketi_9cc975_idx',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='gsheet_mark_marketi_86b1a6_idx',
        ),
        migrations.RenameIndex(
            model_name='five9contact',
            new_name='five9_conta_contact_1e511f_idx',
            old_name='five9_contacts_contact_id_idx',
        ),
        migrations.RenameIndex(
            model_name='five9contact',
            new_name='five9_conta_list_na_e26c70_idx',
            old_name='five9_contacts_list_name_idx',
        ),
        migrations.RenameIndex(
            model_name='five9contact',
            new_name='five9_conta_sys_las_c90994_idx',
            old_name='five9_contacts_sys_last_disposition_time_idx',
        ),
        migrations.RenameIndex(
            model_name='five9contact',
            new_name='five9_conta_sync_up_d9706b_idx',
            old_name='five9_contacts_sync_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='synchistory',
            new_name='sync_histor_crm_sou_43076f_idx',
            old_name='orchestrati_crm_sou_dd1de6_idx',
        ),
        migrations.RenameIndex(
            model_name='synchistory',
            new_name='sync_histor_start_t_7b1b99_idx',
            old_name='orchestrati_start_t_022c6b_idx',
        ),
        migrations.RenameIndex(
            model_name='synchistory',
            new_name='sync_histor_status_ebf158_idx',
            old_name='orchestrati_status_0c02b5_idx',
        ),
        migrations.RemoveField(
            model_name='googlesheetmarketinglead',
            name='marketing_channel',
        ),
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='channel',
            field=models.CharField(blank=True, help_text='Marketing channel (GMB, Google Ads, Bing Ads, Direct Mail, Web Organic, FM Flyer, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_creditapplication',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespro_creditapplication',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salespro_estimate',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespro_estimate',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salespro_office',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespro_office',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salespro_payment',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespro_payment',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salespro_user',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salespro_user',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salespro_useractivity',
            name='sync_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='five9contact',
            unique_together={('number1', 'list_name')},
        ),
        migrations.AddIndex(
            model_name='five9contact',
            index=models.Index(fields=['number1'], name='five9_conta_number1_c44282_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['channel', 'division'], name='gsheet_mark_channel_089373_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['channel', 'created_at'], name='gsheet_mark_channel_7a04c4_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['email'], name='hubspot_con_email_657fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['phone'], name='hubspot_con_phone_3753a2_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['lastmodifieddate'], name='hubspot_con_lastmod_008ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['createdate'], name='hubspot_con_created_fa59ae_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['division'], name='hubspot_con_divisio_6685bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['marketsharp_id'], name='hubspot_con_markets_bf98c2_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['lead_prospect_id'], name='hubspot_con_lead_pr_e092ce_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['lead_status'], name='hubspot_con_lead_st_b49344_idx'),
        ),
        migrations.AddIndex(
            model_name='hubspot_contact',
            index=models.Index(fields=['lead_division'], name='hubspot_con_lead_di_adf332_idx'),
        ),
        migrations.AlterModelTable(
            name='five9contact',
            table='five9_contact',
        ),
        migrations.AlterModelTable(
            name='hubspot_contact',
            table='hubspot_contact',
        ),
        migrations.AlterModelTable(
            name='syncconfiguration',
            table='sync_configuration',
        ),
        migrations.AlterModelTable(
            name='synchistory',
            table='sync_history',
        ),
        migrations.AlterModelTable(
            name='synctracker',
            table='sync_tracker',
        ),
    ]
