# Generated by Django 4.2.23 on 2025-08-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0160_alter_five9contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketingspend',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SalesRabbit_User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('org_id', models.BigIntegerField(blank=True, null=True)),
                ('supervisor_id', models.BigIntegerField(blank=True, null=True)),
                ('recruiter_id', models.BigIntegerField(blank=True, null=True)),
                ('cms_id', models.BigIntegerField(blank=True, null=True)),
                ('lead_rep_cms_id', models.BigIntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('external_ids', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SalesRabbit User',
                'verbose_name_plural': 'SalesRabbit Users',
                'db_table': 'salesrabbit_user',
                'db_table_comment': 'SalesRabbit User/Representative data stored in ingestion schema',
                'managed': True,
                'indexes': [models.Index(fields=['date_modified'], name='salesrabbit_date_mo_85b43f_idx'), models.Index(fields=['email'], name='salesrabbit_email_cc890c_idx'), models.Index(fields=['active'], name='salesrabbit_active_0af9b5_idx'), models.Index(fields=['org_id'], name='salesrabbit_org_id_c64511_idx'), models.Index(fields=['supervisor_id'], name='salesrabbit_supervi_875129_idx'), models.Index(fields=['department'], name='salesrabbit_departm_ba9733_idx'), models.Index(fields=['role'], name='salesrabbit_role_4f0bb6_idx')],
            },
        ),
    ]
