# Generated by Django 4.2.23 on 2025-08-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0162_move_salesrabbit_user_to_ingestion_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesrabbit_user',
            new_name='salesrabbit_date_mo_85b43f_idx',
            old_name='ingestion.s_date_mo_8c0828_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrabbit_user',
            new_name='salesrabbit_email_cc890c_idx',
            old_name='ingestion.s_email_71c9b3_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrabbit_user',
            new_name='salesrabbit_active_0af9b5_idx',
            old_name='ingestion.s_active_f5c244_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrabbit_user',
            new_name='salesrabbit_org_id_c64511_idx',
            old_name='ingestion.s_org_id_9a9496_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrabbit_user',
            new_name='salesrabbit_supervi_875129_idx',
            old_name='ingestion.s_supervi_f538ce_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrabbit_user',
            new_name='salesrabbit_departm_ba9733_idx',
            old_name='ingestion.s_departm_507b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrabbit_user',
            new_name='salesrabbit_role_4f0bb6_idx',
            old_name='ingestion.s_role_df9a5e_idx',
        ),
        migrations.AlterModelTable(
            name='salesrabbit_user',
            table='salesrabbit_user',
        ),
    ]
