# Generated by Django 4.2.23 on 2025-08-26 18:10

from django.db import migrations


def move_table_to_ingestion_schema(apps, schema_editor):
    """Move salesrabbit_user table from django schema to ingestion schema"""
    with schema_editor.connection.cursor() as cursor:
        # Check if table exists in django schema
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = 'django' AND table_name = 'salesrabbit_user'
        """)
        if cursor.fetchone()[0] > 0:
            # Move table from django to ingestion schema
            cursor.execute("ALTER TABLE django.salesrabbit_user SET SCHEMA ingestion;")
            print("Moved salesrabbit_user table from django to ingestion schema")
        else:
            print("Table django.salesrabbit_user not found - no action needed")


def reverse_move_table(apps, schema_editor):
    """Move table back to django schema (reverse operation)"""
    with schema_editor.connection.cursor() as cursor:
        # Check if table exists in ingestion schema
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = 'ingestion' AND table_name = 'salesrabbit_user'
        """)
        if cursor.fetchone()[0] > 0:
            # Move table from ingestion back to django schema
            cursor.execute("ALTER TABLE ingestion.salesrabbit_user SET SCHEMA django;")


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0163_fix_salesrabbit_user_to_ingestion_schema'),
    ]

    operations = [
        migrations.RunPython(move_table_to_ingestion_schema, reverse_move_table),
    ]
