# Generated by Django 4.2.23 on 2025-08-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0164_move_salesrabbit_user_to_ingestion_schema_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespro_user',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Original creation date from SalesPro', null=True),
        ),
        migrations.AddField(
            model_name='salespro_user',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Original last update date from SalesPro', null=True),
        ),
    ]
