# Generated by Django 4.2.23 on 2025-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0165_salespro_user_created_at_salespro_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespro_office',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Original creation date from SalesPro', null=True),
        ),
        migrations.AddField(
            model_name='salespro_office',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Original last update date from SalesPro', null=True),
        ),
    ]
