# Generated by Django 4.2.23 on 2025-08-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0166_salespro_office_created_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS salespro_payment CASCADE;",
            reverse_sql="-- Cannot reverse this migration"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS salespro_user_activity CASCADE;",
            reverse_sql="-- Cannot reverse this migration"
        ),
    ]
