# Generated by Django 4.2.23 on 2025-08-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0167_auto_20250828_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genius_UserAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('definition_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('division_id', models.IntegerField(blank=True, null=True)),
                ('field_value', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genius User Association',
                'verbose_name_plural': 'Genius User Associations',
                'db_table': 'genius_user_association',
                'db_table_comment': 'Genius User Association data stored in ingestion schema',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='genius_appointmentservice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='genius_appointment',
            name='complete_outcome',
        ),
        migrations.RemoveField(
            model_name='genius_appointment',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='genius_appointment',
            name='prospect_source',
        ),
        migrations.RemoveField(
            model_name='genius_appointment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='genius_job',
            name='division',
        ),
        migrations.RemoveField(
            model_name='genius_job',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='genius_job',
            name='service',
        ),
        migrations.RemoveField(
            model_name='genius_jobchangeorder',
            name='job',
        ),
        migrations.RemoveField(
            model_name='genius_jobchangeorderitem',
            name='change_order',
        ),
        migrations.RemoveField(
            model_name='genius_prospect',
            name='division',
        ),
        migrations.RemoveField(
            model_name='genius_prospectsource',
            name='marketing_source',
        ),
        migrations.RemoveField(
            model_name='genius_prospectsource',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='genius_quote',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='genius_quote',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='genius_quote',
            name='service',
        ),
        migrations.RemoveField(
            model_name='genius_userdata',
            name='division',
        ),
        migrations.AddField(
            model_name='genius_appointment',
            name='complete_outcome_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genius_appointment',
            name='prospect_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_appointment',
            name='prospect_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genius_appointment',
            name='type_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_job',
            name='division_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_job',
            name='prospect_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_job',
            name='service_id',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_jobchangeorder',
            name='job_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_jobchangeorderitem',
            name='change_order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_prospect',
            name='division_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_prospectsource',
            name='marketing_source_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_prospectsource',
            name='prospect_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_quote',
            name='appointment_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_quote',
            name='prospect_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_quote',
            name='service_id',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_userdata',
            name='division_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='add_user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='complete_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='confirm_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genius_appointment',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='genius_appointmentservice',
            unique_together={('appointment_id', 'service_id')},
        ),
        migrations.RemoveField(
            model_name='genius_appointmentservice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='genius_appointmentservice',
            name='service',
        ),
    ]
