# Generated by Django 4.2.23 on 2025-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0168_genius_userassociation_delete_salespro_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genius_appointmentservice',
            name='appointment_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genius_appointmentservice',
            name='service_id',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genius_userassociation',
            name='definition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
