# Generated by Django 4.2.23 on 2025-08-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0169_make_user_association_definition_id_nullable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesPro_Payment',
        ),
        migrations.DeleteModel(
            name='SalesPro_UserActivity',
        ),
    ]
