# Generated by Django 4.2.23 on 2025-09-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingestion', '0170_delete_salespro_payment_delete_salespro_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('mode', models.CharField(choices=[('delta', 'Delta'), ('full', 'Full')], max_length=16)),
                ('recurrence_type', models.CharField(choices=[('interval', 'Interval'), ('crontab', 'Crontab')], max_length=16)),
                ('every', models.PositiveIntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=16, null=True)),
                ('minute', models.CharField(blank=True, default='0', max_length=64, null=True)),
                ('hour', models.CharField(blank=True, default='*', max_length=64, null=True)),
                ('day_of_week', models.CharField(blank=True, default='*', max_length=64, null=True)),
                ('day_of_month', models.CharField(blank=True, default='*', max_length=64, null=True)),
                ('month_of_year', models.CharField(blank=True, default='*', max_length=64, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_schedules', 'Can manage ingestion schedules')],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped_overlap', 'Skipped (Overlap)')], max_length=32)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ingestion.ingestionschedule')),
            ],
        ),
        migrations.AddIndex(
            model_name='ingestionschedule',
            index=models.Index(fields=['source_key', 'mode'], name='ingestion_i_source__f9f633_idx'),
        ),
    ]
