# Generated by Django 4.2.23 on 2025-09-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0173_delete_synctracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncschedule',
            options={'managed': True, 'permissions': [('manage_schedules', 'Can manage ingestion schedules')]},
        ),
        migrations.RenameIndex(
            model_name='syncschedule',
            new_name='orchestrati_source__67e833_idx',
            old_name='ingestion_i_source__f9f633_idx',
        ),
    ]
