# Generated by Django 4.2.23 on 2025-09-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0176_update_db_table_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncschedule',
            new_name='sync_schedu_source__daaf9f_idx',
            old_name='orchestrati_source__67e833_idx',
        ),
    ]
