# Generated by Django 4.2.23 on 2025-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0177_rename_orchestrati_source__67e833_idx_sync_schedu_source__daaf9f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncschedule',
            name='crm_source',
            field=models.CharField(db_index=True, default='NA', help_text='CRM source (e.g., genius, hubspot)', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='model_name',
            field=models.CharField(default='NA', help_text='Model name to sync (e.g., appointments, contacts)', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='day_of_month',
            field=models.CharField(blank=True, default='*', help_text='Day of month (1-31)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='day_of_week',
            field=models.CharField(blank=True, default='*', help_text='Day of week (0-6, Monday is 1)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this schedule is active'),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='When to stop running this schedule', null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='every',
            field=models.PositiveIntegerField(blank=True, help_text='Every X periods', null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='hour',
            field=models.CharField(blank=True, default='*', help_text='Hour (0-23)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='minute',
            field=models.CharField(blank=True, default='0', help_text='Minute (0-59)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='mode',
            field=models.CharField(choices=[('delta', 'Delta - Import since last import'), ('full', 'Full - Delete everything and import again'), ('force7', 'Force7 - Import last 7 days with --force flag')], help_text='Sync mode', max_length=16),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='month_of_year',
            field=models.CharField(blank=True, default='*', help_text='Month of year (1-12)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='name',
            field=models.CharField(help_text='Descriptive name for this schedule', max_length=128),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Additional options as JSON'),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='period',
            field=models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], help_text='Period unit for interval schedules', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='recurrence_type',
            field=models.CharField(choices=[('interval', 'Interval'), ('crontab', 'Crontab')], help_text='Type of recurrence schedule', max_length=16),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='source_key',
            field=models.CharField(db_index=True, help_text='Auto-generated from crm_source', max_length=64),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='When to start running this schedule', null=True),
        ),
    ]
