# Generated by Django 4.2.23 on 2025-09-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0178_syncschedule_crm_source_syncschedule_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='cc_profile_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='docusign_acct_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='intern_payroll_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='mes_profile_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='mes_profile_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='painter_payroll_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='paysimple_secret',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='genius_divisiongroup',
            name='paysimple_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='genius_divisiongroup',
            name='default_time_zone_name',
            field=models.CharField(default='US/Pacific', max_length=64),
        ),
        migrations.AlterField(
            model_name='genius_divisiongroup',
            name='group_label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
