# Generated by Django 4.2.23 on 2025-09-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0179_genius_divisiongroup_cc_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genius_DivisionRegion',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genius Division Region',
                'verbose_name_plural': 'Genius Division Regions',
                'db_table': 'genius_division_region',
                'db_table_comment': 'Genius Division Region data stored in ingestion schema',
                'managed': True,
            },
        ),
    ]
