# Generated by Django 4.2.23 on 2025-09-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0180_genius_divisionregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspot_contact',
            name='address_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='canvasser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='canvasser_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='canvasser_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='contact_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='contact_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='currentlyinworkflow',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='dedupe_record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='division_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hatch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hge_primary_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hge_secondary_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_average_page_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_first_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_num_event_completions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_num_page_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_num_visits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_source_data_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_analytics_source_data_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_created_by_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_currently_enrolled_in_prospecting_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_email_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_is_unworked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_latest_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_latest_source_data_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_latest_source_data_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_latest_source_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_marketable_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_marketable_until_renewal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_membership_has_accessed_private_content',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_object_source_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_predictivecontactscore_v2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_predictivescoringtier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_prospecting_agent_total_enrolled_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_registered_member',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_updated_by_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='hs_v2_date_entered_lead',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='last_scheduled_appointment_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='lifecyclestage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='notes_last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='notes_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='num_contacted_notes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='num_conversion_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='num_notes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='num_unique_conversion_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='phone1_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='phone2_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_add_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_is_address_valid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_is_year_built_valid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_marketsharp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_phone1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_phone1_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_phone2_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='prospect_year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='sales_rabbit_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hubspot_contact',
            name='service_of_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
