# Generated by Django 4.2.23 on 2025-09-12 15:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0181_hubspot_contact_address_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genius_JobFinancing',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('term_id', models.IntegerField(blank=True, null=True)),
                ('financed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('max_financed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('bid_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('commission_reduction', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('signed_on', models.DateTimeField(blank=True, null=True)),
                ('cancellation_period_expires_on', models.DateTimeField(blank=True, null=True)),
                ('app_submission_date', models.DateTimeField(blank=True, null=True)),
                ('is_joint_application', models.SmallIntegerField(default=0)),
                ('applicant', models.CharField(blank=True, max_length=50, null=True)),
                ('co_applicant', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('loan_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('denied_on', models.DateTimeField(blank=True, null=True)),
                ('denied_by', models.IntegerField(blank=True, null=True)),
                ('why_book', models.TextField(blank=True, null=True)),
                ('would_book', models.SmallIntegerField(blank=True, null=True)),
                ('is_financing_factor', models.SmallIntegerField(blank=True, null=True)),
                ('satisfied', models.TextField(blank=True, null=True)),
                ('docs_completed', models.DateTimeField(blank=True, null=True)),
                ('active_stipulation_notes', models.TextField(blank=True, null=True)),
                ('is_active_stipulations_cleared', models.SmallIntegerField(default=0)),
                ('legal_app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genius Job Financing',
                'verbose_name_plural': 'Genius Job Financings',
                'db_table': 'genius_job_financing',
                'db_table_comment': 'Genius Job Financing data stored in ingestion schema',
                'managed': True,
            },
        ),
    ]
