# Generated by Django 4.2.23 on 2025-09-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0182_genius_jobfinancing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genius_jobfinancing',
            table='ingestion.job_financing',
        ),
    ]
