# Generated by Django 4.2.23 on 2025-09-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0184_alter_genius_jobfinancing_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genius_jobfinancing',
            table='"genius_job_financing"',
        ),
    ]
