# Generated by Django 4.2.23 on 2025-09-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0185_alter_genius_jobfinancing_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_prospect',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
