# Generated by Django 4.2.23 on 2025-09-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0186_alter_genius_prospect_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_prospectsource',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='genius_quote',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
