# Generated by Django 4.2.23 on 2025-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0187_alter_genius_prospectsource_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genius_appointment',
            name='add_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='genius_job',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
