# Generated by Django 4.2.23 on 2025-09-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0188_alter_genius_appointment_add_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubspot_contact',
            name='primary_source',
        ),
        migrations.RemoveField(
            model_name='hubspot_contact',
            name='secondary_source',
        ),
    ]
