# Generated by Django 4.2.23 on 2025-09-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0189_remove_hubspot_contact_primary_source_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genius_jobfinancing',
            table='genius_job_financing',
        ),
    ]
