# Generated by Django 4.2.23 on 2025-09-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0190_alter_genius_jobfinancing_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespro_estimate',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Original creation date from SalesPro', null=True),
        ),
        migrations.AddField(
            model_name='salespro_estimate',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Original last update date from SalesPro', null=True),
        ),
    ]
