# Generated by Django 4.2.24 on 2025-10-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0193_add_year_id_to_marketing_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPro_LeadResultLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_number', models.PositiveSmallIntegerField()),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Lead Result Line Item',
                'verbose_name_plural': 'Lead Result Line Items',
                'db_table': 'salespro_lead_result_line_item',
                'db_table_comment': 'SalesPro Lead Result Line Items stored in ingestion schema',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='googlesheetmarketinglead',
            options={'managed': True, 'ordering': ['-created_at', '-sync_created_at'], 'verbose_name': 'Google Sheet Marketing Lead', 'verbose_name_plural': 'Google Sheet Marketing Leads'},
        ),
        migrations.AlterModelTableComment(
            name='googlesheetmarketinglead',
            table_comment='Google Sheet Marketing Lead data stored in ingestion schema',
        ),
        migrations.RemoveIndex(
            model_name='googlesheetmarketinglead',
            name='gsheet_mark_sync_created_idx',
        ),
        migrations.RenameIndex(
            model_name='googlesheetmarketinglead',
            new_name='gsheet_mark_year_8150f2_idx',
            old_name='gsheet_mark_year_row_idx',
        ),
        migrations.RenameIndex(
            model_name='googlesheetmarketinglead',
            new_name='gsheet_mark_year_da2293_idx',
            old_name='gsheet_mark_year_created_idx',
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='additional_services_demoed_priced',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='balance_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='call_to_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='client_most_likely_to_add_on',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='closing_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='color_selection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='company_story_pain_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='customers_final_price_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='deadline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='deposit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='describe_rapport_hot_button',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='details_discussed_for_install',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='did_use_company_cam',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='dumpster_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='financing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='financing_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='has_consider_solar',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='job_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='last_payment_offered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='loan_docs_signed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='measurement_tool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='no_brainer_commitment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='notes_for_install_team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='price_conditioning_response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='requested_start_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='sales_manager_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='scheduling_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='st8_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='status_bucket',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='timing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='total_job_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='upload_estimate_sheet_company_cam',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='urgency_time_frame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salespro_leadresult',
            name='warm_up_topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='adgroup_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='adgroup_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='appt_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='appt_result_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='call_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='call_recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='callback_review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='channel',
            field=models.CharField(blank=True, help_text='Marketing channel (GMB, Google Ads, Bing Ads, Direct Mail, Web Organic, FM Flyer, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='click_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='click_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='contact_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='created_at from sheet', null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='event_show_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='event_show_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='f9_last_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='f9_list_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='genius_marketing_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='google_ads_campaign_rename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='hold_time',
            field=models.IntegerField(blank=True, help_text='Hold time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='last_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='lead_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='marketing_zip_check',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='marketsharp_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='marketsharp_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='no_set_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='page_source_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='page_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Complete row data from sheet'),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='recording_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='sheet_last_modified',
            field=models.DateTimeField(blank=True, help_text='Sheet last modification time', null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_creditapplication',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salespro_customer',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salespro_estimate',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='both_homeowners_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='company_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='lead_results_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salespro_leadresult',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salespro_office',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salespro_user',
            name='sync_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['phone_number', 'created_at'], name='gsheet_mark_phone_n_186cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['email_address', 'created_at'], name='gsheet_mark_email_a_f8dfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['first_name', 'last_name'], name='gsheet_mark_first_n_caa228_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['utm_campaign', 'division'], name='gsheet_mark_utm_cam_59e647_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['genius_marketing_source', 'division'], name='gsheet_mark_genius__0722e3_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['created_at', 'utm_campaign'], name='gsheet_mark_created_d99ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['channel', 'division'], name='gsheet_mark_channel_089373_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['channel', 'created_at'], name='gsheet_mark_channel_7a04c4_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['lead_set', 'division'], name='gsheet_mark_lead_se_762825_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['connection_status', 'lead_type'], name='gsheet_mark_connect_a1a7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['appt_result', 'appointment_outcome'], name='gsheet_mark_appt_re_8bc5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['sheet_row_number'], name='gsheet_mark_sheet_r_87f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['created_at'], name='gsheet_mark_created_bda6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['division', 'created_at', 'lead_set'], name='gsheet_mark_divisio_e7f095_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_leadresult',
            index=models.Index(fields=['company_id'], name='salespro_le_company_8ab219_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_leadresult',
            index=models.Index(fields=['appointment_result'], name='salespro_le_appoint_7ef50d_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_leadresult',
            index=models.Index(fields=['status_bucket'], name='salespro_le_status__086494_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_leadresult',
            index=models.Index(fields=['job_size'], name='salespro_le_job_siz_81ba91_idx'),
        ),
        migrations.AddIndex(
            model_name='salespro_leadresult',
            index=models.Index(fields=['sync_updated_at'], name='salespro_le_sync_up_fee7ac_idx'),
        ),
        migrations.AddField(
            model_name='salespro_leadresultlineitem',
            name='estimate',
            field=models.ForeignKey(db_column='estimate_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ingestion.salespro_leadresult'),
        ),
        migrations.AddIndex(
            model_name='salespro_leadresultlineitem',
            index=models.Index(fields=['estimate', 'job_type_number'], name='salespro_le_estimat_e080d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salespro_leadresultlineitem',
            unique_together={('estimate', 'job_type_number')},
        ),
    ]
