# Generated by Django 4.2.24 on 2025-10-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0194_update_salespro_leadresult_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genius_IntegrationField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('definition_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('division_id', models.IntegerField(blank=True, null=True)),
                ('field_value', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genius Integration Field',
                'verbose_name_plural': 'Genius Integration Fields',
                'db_table': 'genius_integration_field',
                'db_table_comment': 'Genius Integration Field data stored in ingestion schema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genius_IntegrationFieldDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('integration_id', models.IntegerField()),
                ('label', models.CharField(max_length=32)),
                ('key_name', models.CharField(max_length=64)),
                ('is_user', models.BooleanField(default=False)),
                ('is_division', models.BooleanField(default=False)),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
                ('input_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genius Integration Field Definition',
                'verbose_name_plural': 'Genius Integration Field Definitions',
                'db_table': 'genius_integration_field_definition',
                'db_table_comment': 'Genius Integration Field Definition data stored in ingestion schema',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='genius_prospectsource',
            name='source_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
