# Generated by Django 4.2.23 on 2025-10-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0195_genius_integrationfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetmarketinglead',
            name='page_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
