# Generated by Django 4.2.25 on 2025-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0196_increase_page_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetmarketingspend',
            name='campaign_id',
            field=models.CharField(blank=True, help_text='Campaign ID from Google Ads or other platforms', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketingspend',
            name='campaign_type',
            field=models.CharField(blank=True, help_text='Campaign type (SEARCH, DISPLAY, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketingspend',
            name='event_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Event registration or venue fee', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='googlesheetmarketingspend',
            name='event_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Labor cost for event participation', max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketingspend',
            index=models.Index(fields=['campaign_id', 'spend_date'], name='gsheet_mark_campaig_cf80d6_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketingspend',
            index=models.Index(fields=['campaign_type', 'channel'], name='gsheet_mark_campaig_3b41cf_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketingspend',
            index=models.Index(fields=['event_fee', 'event_labor_cost'], name='gsheet_mark_event_f_c9a463_idx'),
        ),
    ]
