# Generated by Django 4.2.25 on 2025-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0197_googlesheetmarketingspend_campaign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetmarketinglead',
            name='event_field_marketer',
            field=models.CharField(blank=True, help_text='Field marketer assigned to event', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='googlesheetmarketinglead',
            index=models.Index(fields=['event_field_marketer', 'created_at'], name='gsheet_mark_event_f_09867d_idx'),
        ),
    ]
