services:
  web:
    build: .
    command: bash -c "if [ ! -f manage.py ]; then django-admin startproject data_warehouse .; fi && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A data_warehouse worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A data_warehouse beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  test:
    build: .
    command: python test_hubspot_docker.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=data_warehouse.settings