services:
  web:
    build: .
    command: bash -c "if [ ! -f manage.py ]; then django-admin startproject data_warehouse .; fi && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8080:8080"  # For Google OAuth2 callback
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A data_warehouse worker --concurrency=2 --prefetch-multiplier=1 --max-tasks-per-child=50 --max-memory-per-child=300000 -l info -Q dw-local
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A data_warehouse beat -l info -S django
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  adk:
    build: .
    command: python /app/patch_and_run_adk.py
    ports:
      - "7860:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  test:
    build: .
    command: python ingestion/tests/test_hubspot_docker.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=data_warehouse.settings